#!/usr/bin/env php

<?php

use function Differ\Differ\parseInput;
use function Differ\Differ\getFilePathsFromInput;
use function Differ\Differ\genDiff;
use function Differ\Differ\getFormat;

require_once __DIR__ . '/vendor/autoload.php';

$input = parseInput();
[$firstFile, $secondFile] = getFilePathsFromInput($input);
$format = getFormat($input);

try {
    $format = $format ?? 'stylish';
    $diff = genDiff($firstFile, $secondFile, $format);

    if ($diff) {
        print_r($diff);
    }
} catch (\Exception $exception) {
    print_r($exception->getMessage());
}



