#!/usr/bin/env php

<?php

use function Differ\Differ\getArgs;
use function Differ\Differ\getFilePathsFromArgs;
use function Differ\Differ\genDiff;
use function Differ\Differ\getFormat;

require_once __DIR__ . '/vendor/autoload.php';

$args = getArgs();
[$firstFile, $secondFile] = getFilePathsFromArgs($args);
$format = getFormat($args);

try {
    $format = $format ?? 'stylish';
    $diff = genDiff($firstFile, $secondFile, $format);

    if ($diff) {
        print_r($diff);
    }
} catch (\Exception $exception) {
    print_r($exception->getMessage());
}



